# Generated by Django 4.1.7 on 2024-02-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name": "notes", "verbose_name_plural": "notes"},
        ),
    ]
